### PR TITLE
Feat/1014 deploy

### PR DESCRIPTION
**Pull request by zjimf**

### CODE REVIEW

**Comment by zjimf** [comment]
Here is the cicd architecture, .env, nginx.conf, docker-compose.yaml is on the server side

These three files should be able to be updated synchronously during CD, but for some reasons the files cannot be found during CD.(that's why the commit is a little bit ugly)

It seems that it cannot be done until merging into the **main** branch, otherwise these three files will need to be updated every time. It’s a bit troublesome to have to update on the server side.

SystemDesign drawio

**Comment by HenryHung90** [comment]
@zjimf  actually you can using `git reset HEAD~` and commit again, then `git push -f`, this way can overwrite your commit.

**Comment by zjimf** [comment]
> @zjimf actually you can using `git reset HEAD~` and commit again, then `git push -f`, this way can overwrite your commit.

check it out

**Review by 1092024 — APPROVED** [review]

**Review by HenryHung90 — APPROVED** [review]
Good To Go

**Pull request merged**
